# Generated by Django 4.2.4 on 2024-09-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='author',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='saved_by',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='url',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='authors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='citations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
