# Generated by Django 4.2.4 on 2024-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_remove_researchpaper_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='authors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='citations',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
