# Generated by Django 4.2.4 on 2024-09-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_researchpaper_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
